### ISSUE TITLE
How does the d3 .js and css get loaded?

### ISSUE THREAD

**Issue by andybak** [areski/django-admin-tools-stats#14]
Nothing in the instructions mentions it so I was assuming it happened by magic.

However there's nothing there when I view source or look for network requests. Digging in the django-nvd3 code reveals some docstrings that mention a template tag to load all the media. Should this be in my admin templates?

**Comment by bendwarn** [comment]
I suggest using original cdn of those files in templates, because the number of files is small, and this module is for admin, so cdn fails is not a big deal in production.

**Comment by andybak** [comment]
I just returned to this project and forgot I'd posted this issue!

I still saw 'bower' in the readme and thought 'damn. maybe not' - the reasons are slightly different now. I am much more likely to introduce webpack as a build dependency and having two build tools running in a project is rather alarming. 

I think the general question is this "Should an app that I add to my project be opinionated about my build pipeline? Surely that's a project-level decision? What if several apps all want different build tools?"

**Comment by areski** [comment]
@andybak I totally agree with you! This project should be not take decision for you, specially not on how you manage your assets. Django-admin-tools-stats dont really need bower but it needs to find the d3/nvd3 css/js. A quick fix would be to include cdn by default and remove the bower part from the doc.

**Comment by andybak** [comment]
That would be a great default. Maybe also add a setting (ADMIN_TOOLS_STATS_D3_URL ? ) with the logic that relative paths are relative to STATIC_URL ?

That makes it easy for people to do whatever they want - including use bower.

**Comment by areski** [comment]
I'm very busy at the moment, so I would appreciate a PR if someone can do this.

**Comment by andybak** [comment]
I've come across this again on another project and I think the correct solution is:

1. Use a CDN by default (pick the most popular one possible)
2. Have an optional setting to override this with either a different CDN or a URL for a local static file 

This gives a simple working default and an easy way for projects to do what suits them.

I'll try and do some work on this myself.

**Comment by areski** [comment]
Thanks!
