### ISSUE TITLE
Using django-admin-tools-stats in Django Jet

### ISSUE THREAD

**Issue by alirezaafzalaghaei** [areski/django-admin-tools-stats#36]
Can i use this module in [django-jet ](https://github.com/geex-arts/django-jet)admin interface? If yes, How can i configure it?

**Comment by areski** [comment]
This is not compatible with django-jet, but you are welcome to extract the code and implement a version that work with django-get

**Comment by TrungKien1230** [comment]
@alirezaafzalaghaei  Have you tried it with django jet ? If yes, could you please show me how to to that ?
